 print("Ce nume si prenume ai?") 
 np=str(input("Numele si prenumele este: ")) 
 print(np) 
 print("Ce iti doresti sa devii in viitor?") 
 p=str(input("Profesia este: ")) 
 print(p) 
 print("Te numesti",np) 
 print("Doresti sa devii",p) 